/* eslint-disable */
// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "app.getAppInfo", input: never, result: AppInfo } | 
        { key: "config.getConfig", input: never, result: Config },
    mutations: 
        { key: "config.setAppConfig", input: AppConfig, result: null } | 
        { key: "config.setVpnConfig", input: VpnConfig[], result: null } | 
        { key: "vpn.start", input: string, result: null } | 
        { key: "vpn.stop", input: never, result: null },
    subscriptions: 
        { key: "app.connectionStatus", input: never, result: Status } | 
        { key: "app.log", input: never, result: LogEntry }
};

export type AppConfig = { proxy: ProxyConfig; vpn_global: GlobalVpnConfig; auto_start: AutoStartConfig }

export type AutoStartConfig = { app: boolean; vpn: string | null; hide_window: boolean }

export type ProxyConfig = { enabled: boolean; proxy_port: number }

export type VpnConfig = { id: string; interface: VpnInterface; peer: VpnPeer }

export type LogEntry = { VpnLog: VpnLog } | { AppLog: AppLog }

export type Level = "Trace" | "Debug" | "Info" | "Warn" | "Error"

export type VpnLog = { level: Level; vpn_id: string; message: string }

export type Config = { app: AppConfig; vpn: VpnConfig[] }

export type AppLog = { level: Level; message: string }

export type Status = "Disconnected" | { Connected: string } | { Connecting: string } | { Disconnecting: string }

export type AppInfo = { name: string; version: string }

export type VpnPeer = { public_key: string; allowed_ips: string; endpoint: string; preshared_key: string | null; allowed_apps: string | null; disallowed_apps: string | null; disallowed_ips: string | null }

export type VpnInterface = { private_key: string; address: string; dns: string | null; mtu: string | null }

export type GlobalVpnConfig = { dns: string | null; allowed_ips: string | null; disallowed_ips: string | null; allowed_apps: string | null; disallowed_apps: string | null }
