/* eslint-disable */
// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "app.getAppInfo", input: never, result: AppInfo },
    mutations: never,
    subscriptions: never
};

export type AppInfo = { version: string }
